/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LimitedPhotographies } from "./LimitedPhotographies";

export { LimitedPhotographies__factory } from "./factories/LimitedPhotographies__factory";
